# Generated by Django 3.2.16 on 2025-04-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм'),
        ),
    ]
