# Generated by Django 3.2.16 on 2025-04-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='nickname',
        ),
    ]
