# Generated by Django 5.1.7 on 2025-04-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка урока')),
                ('lesson_number', models.IntegerField(verbose_name='Номер урока')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрытый')),
            ],
        ),
        migrations.CreateModel(
            name='MatchLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Текст варианта ответа')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Текст варианта ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50, verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('input', 'Input'), ('single_choices', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('mathcing', 'Matching')], max_length=15, verbose_name='Тип вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст параграфа')),
                ('order', models.IntegerField(verbose_name='Порядок параграфов')),
                ('lesson_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='ID Урока')),
            ],
        ),
        migrations.CreateModel(
            name='MatchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.matchleft', verbose_name='ID левого варианта ответа')),
                ('right_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.matchright', verbose_name='ID правого варианта ответа')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='ID вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='InputQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.CharField(max_length=50, verbose_name='Правильный ответ')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='ID вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Текст варианта ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='ID вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название предмета')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='ID предмета'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя теста')),
                ('lesson_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='ID Урока')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.test', verbose_name='ID теста'),
        ),
    ]
