# Generated by Django 3.2.16 on 2025-04-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20250419_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='lesson',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
    ]
