# Generated by Django 3.2.16 on 2025-04-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20250420_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicequestion_set', to='courses.question', verbose_name='ID вопроса'),
        ),
        migrations.AlterField(
            model_name='inputquestion',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inputquestion', to='courses.question', verbose_name='ID вопроса'),
        ),
    ]
